Nettoyage PUBLIC RECORDS (un ipynb qui regroupe toutes les fonctions pour créer un csv nettoyé par fichier)

In [27]:
import pandas as pd
import numpy as np
from pathlib import Path

In [28]:
# il y a des textes qui sont trop longs pour être affichés dans le notebook, on les tronque à 60 caractères
pd.set_option("display.max_colwidth", 60)

In [29]:
DATA_DIR = Path(".")
files = files = sorted([
    f for f in DATA_DIR.glob("*.csv")
    if not f.name.endswith("_cleaned.csv")
])
print([f.name for f in files])

raw_dfs = {f.stem: pd.read_csv(f) for f in files}

['institutional_memos.csv', 'licensed_facilities.csv', 'licensed_professionals.csv', 'officer_filings.csv', 'public_and_investigative_documents.csv', 'public_appointments.csv', 'registered_entities.csv', 'regulatory_case_events.csv', 'site_access_case_events.csv']

In [30]:
def profile_df(df: pd.DataFrame, name: str, n_sample: int = 3) -> None:
    print(f"=== {name} : {df.shape[0]} lignes, {df.shape[1]} colonnes ===")
    print(df.dtypes)
    print("\nManquants (%) :")
    print((df.isna().mean() * 100).round(2))
    print("\nLignes dupliquées (strictes) :", df.duplicated().sum())

    print(f"\nÉchantillon ({n_sample} lignes) :")
    display(df.sample(n_sample))

for f in files:
    df = pd.read_csv(f)
    print(f"\n=== {f.name} ({df.shape[0]} lignes, {df.shape[1]} colonnes) ===")
    print(df.columns.tolist())
    
for name, df in raw_dfs.items():
    profile_df(df, name)

=== institutional_memos.csv (30 lignes, 12 colonnes) ===
['document_id', 'document_date', 'document_type', 'author_name', 'author_organization', 'recipient_text', 'subject_line', 'text', 'related_purchase_order', 'related_shipment_number', 'related_case_number', 'visibility_level']

=== licensed_facilities.csv (3 lignes, 12 colonnes) ===
['facility_license_number', 'facility_name', 'facility_category', 'operating_organization_registration', 'street_address', 'region', 'latitude', 'longitude', 'license_start', 'license_end', 'facility_status', 'declared_services']

=== licensed_professionals.csv (53 lignes, 10 colonnes) ===
['license_number', 'professional_name', 'profession', 'specialty', 'license_issue_date', 'license_expiry_date', 'license_status', 'primary_facility_license', 'registered_region', 'disciplinary_status']

=== officer_filings.csv (136 lignes, 12 colonnes) ===
['filing_id', 'registration_number', 'officer_local_ref', 'full_name', 'birth_year_or_age_band', 'nationality_or_region', 'role_title', 'appointment_date', 'cessation_date', 'filing_date', 'service_address', 'filing_status']

=== public_and_investigative_documents.csv (40 lignes, 11 colonnes) ===
['document_id', 'document_date', 'collection', 'document_type', 'author_name', 'author_organization', 'named_location', 'title', 'text', 'public_or_restricted', 'source_reference']

=== public_appointments.csv (62 lignes, 12 colonnes) ===
['appointment_record_id', 'appointing_jurisdiction', 'office_holder_name', 'recorded_birth_year', 'office_title', 'institution_name', 'appointment_start', 'appointment_end', 'appointment_basis', 'departure_reason', 'official_region', 'source_notice_reference']

=== registered_entities.csv (24 lignes, 10 colonnes) ===
['registration_number', 'legal_name', 'registered_entity_type', 'registration_date', 'current_status', 'registered_address', 'jurisdiction', 'declared_activity', 'parent_registration_number', 'last_filing_date']

=== regulatory_case_events.csv (233 lignes, 16 colonnes) ===
['regulatory_event_id', 'case_number', 'case_category', 'event_time', 'activity', 'subject_name', 'subject_registration_number', 'agency_name', 'initiating_source', 'assigned_unit', 'related_site_code', 'related_shipment_number', 'previous_status', 'new_status', 'outcome', 'public_reference']

=== site_access_case_events.csv (413 lignes, 15 colonnes) ===
['access_event_id', 'access_case_number', 'site_code', 'event_time', 'activity', 'requesting_organization_name', 'requesting_registration_number', 'authorizing_agency', 'authorized_person_name', 'access_purpose', 'equipment_category', 'previous_status', 'new_status', 'confidentiality_class', 'outcome']
=== institutional_memos : 30 lignes, 12 colonnes ===
document_id                str
document_date              str
document_type              str
author_name                str
author_organization        str
recipient_text             str
subject_line               str
text                       str
related_purchase_order     str
related_shipment_number    str
related_case_number        str
visibility_level           str
dtype: object

Manquants (%) :
document_id                 0.00
document_date               0.00
document_type               0.00
author_name                 0.00
author_organization         0.00
recipient_text              0.00
subject_line                0.00
text                        0.00
related_purchase_order     83.33
related_shipment_number    73.33
related_case_number        66.67
visibility_level            0.00
dtype: float64

Lignes dupliquées (strictes) : 0

Échantillon (3 lignes) :

,document_id,document_date,document_type,author_name,author_organization,recipient_text,subject_line,text,related_purchase_order,related_shipment_number,related_case_number,visibility_level
16,MEM-510047,2025-10-25,shipment_report,Ilia Toren,Valenne Industrial Futures Council,"Operations, finance, and compliance",Shipment Exception Report 69,ROUTE\nShipment moved between the recorded origin and d...,NaN,NaN,REG-2024-0009,internal
19,MEM-510125,2018-01-19,inventory_explanation,Bela Ferran,Helix Legal and Compliance,"Operations, finance, and compliance",Inventory Reconciliation Explanation 72,PERIOD\nInventory explanation related to ADJ-2024-00117....,NaN,NaN,NaN,internal
22,MEM-510089,2019-04-13,security_instruction,Nadia Aren,Nivren Maritime Logistics,"Operations, finance, and compliance",Records Security Instruction 75,SCOPE\nSecurity instruction for inventory close and asso...,PO-2025-00039,NaN,NaN,internal

=== licensed_facilities : 3 lignes, 12 colonnes ===
facility_license_number                    str
facility_name                              str
facility_category                          str
operating_organization_registration        str
street_address                             str
region                                     str
latitude                               float64
longitude                              float64
license_start                              str
license_end                            float64
facility_status                            str
declared_services                          str
dtype: object

Manquants (%) :
facility_license_number                  0.0
facility_name                            0.0
facility_category                        0.0
operating_organization_registration      0.0
street_address                           0.0
region                                   0.0
latitude                                 0.0
longitude                                0.0
license_start                            0.0
license_end                            100.0
facility_status                          0.0
declared_services                        0.0
dtype: float64

Lignes dupliquées (strictes) : 0

Échantillon (3 lignes) :

,facility_license_number,facility_name,facility_category,operating_organization_registration,street_address,region,latitude,longitude,license_start,license_end,facility_status,declared_services
1,FAC-AVL-201,Asterion Avelora Executive Clinic,private_clinic,REG-VLN-01002,"Asterion Avelora Executive Clinic, Eastern Avelora Agric...",Avelora Federation,7.35,101.62,2008-05-15,NaN,active,executive health; specialist follow-up; outpatient proce...
2,FAC-AVL-301,Threshold Earth Avelora Laboratory,research_laboratory,REG-AVL-01007,"Threshold Earth Avelora Laboratory, Eastern Avelora Agri...",Avelora Federation,7.50,101.75,2012-01-18,NaN,active,environmental health research; non-invasive human assess...
0,FAC-VLN-101,Asterion Central Clinical Campus,research_hospital,REG-VLN-01002,"Asterion Central Clinical Campus, Valenne Central District",Valenne Republic,47.20,7.51,2001-02-01,NaN,active,preventive medicine; cardiac assessment; clinical research

=== licensed_professionals : 53 lignes, 10 colonnes ===
license_number                  str
professional_name               str
profession                      str
specialty                       str
license_issue_date              str
license_expiry_date         float64
license_status                  str
primary_facility_license        str
registered_region               str
disciplinary_status             str
dtype: object

Manquants (%) :
license_number                0.00
professional_name             0.00
profession                    0.00
specialty                     0.00
license_issue_date            0.00
license_expiry_date         100.00
license_status                0.00
primary_facility_license     49.06
registered_region             0.00
disciplinary_status           0.00
dtype: float64

Lignes dupliquées (strictes) : 0

Échantillon (3 lignes) :

,license_number,professional_name,profession,specialty,license_issue_date,license_expiry_date,license_status,primary_facility_license,registered_region,disciplinary_status
30,LIC-VLN-ADM-1031,Bela Wessen,public administration professional,programme administration,2016-07-01,NaN,active,NaN,Valennan,none
33,LIC-TMB-ADM-1034,Jalen Quorin,public administration professional,programme administration,2013-07-01,NaN,active,NaN,Tembaran,resolved administrative review
10,LIC-VLN-RES-1011,Mara Venn,research professional,clinical research,2006-07-01,NaN,active,FAC-AVL-301,Valennan,none

=== officer_filings : 136 lignes, 12 colonnes ===
filing_id                 str
registration_number       str
officer_local_ref         str
full_name                 str
birth_year_or_age_band    str
nationality_or_region     str
role_title                str
appointment_date          str
cessation_date            str
filing_date               str
service_address           str
filing_status             str
dtype: object

Manquants (%) :
filing_id                  0.00
registration_number        0.00
officer_local_ref          0.00
full_name                  0.00
birth_year_or_age_band     0.00
nationality_or_region      0.00
role_title                 0.00
appointment_date           0.00
cessation_date            56.62
filing_date                0.00
service_address            0.00
filing_status              0.00
dtype: float64

Lignes dupliquées (strictes) : 1

Échantillon (3 lignes) :

,filing_id,registration_number,officer_local_ref,full_name,birth_year_or_age_band,nationality_or_region,role_title,appointment_date,cessation_date,filing_date,service_address,filing_status
34,FLG-000035,REG-AVL-01009,OFR-20033,Liora Maren,1980–1989,Kintaran,Deputy director,2011-01-01,2016-12-31,2011-03-13,Eastern Avelora Agricultural Cluster,historical
86,FLG-000087,REG-AVL-01007,OFR-20083,Calen Elen,1970–1979,Tembaran,Programme manager,1995-01-01,2000-12-31,1995-03-09,Threshold Earth Avelora Laboratory,historical
39,FLG-000040,REG-VLN-01008,OFR-20039,Wira Soren,1983,Valennan,Campaign coordinator,2016-01-01,NaN,2016-02-15,Valenne Central District,active

=== public_and_investigative_documents : 40 lignes, 11 colonnes ===
document_id             str
document_date           str
collection              str
document_type           str
author_name             str
author_organization     str
named_location          str
title                   str
text                    str
public_or_restricted    str
source_reference        str
dtype: object

Manquants (%) :
document_id             0.0
document_date           0.0
collection              0.0
document_type           0.0
author_name             2.5
author_organization     0.0
named_location          0.0
title                   0.0
text                    0.0
public_or_restricted    0.0
source_reference        0.0
dtype: float64

Lignes dupliquées (strictes) : 0

Échantillon (3 lignes) :

,document_id,document_date,collection,document_type,author_name,author_organization,named_location,title,text,public_or_restricted,source_reference
22,PUB-510071,2021-06-05,public_interest_archive,open_letter,Jora Menne,Lantern Investigative Bureau,Valenne Central District,Open Letter on Public Records 97,TO THE RESPONSIBLE INSTITUTIONS\nWe write concerning com...,public,REF-2021-07097
5,PUB-510079,2025-04-09,investigative_repository,whistleblower_message,Mara Venn,Lantern Investigative Bureau,Valenne Central District,Message Concerning Collected Eonycteris,I worked on restricted receiving and reconciliation reco...,restricted,ARC-2025-0113
9,PUB-510103,2022-01-22,official_repository,policy_memorandum,Kellan Orell,Office of the Kintara Chancellor,Kintara Republic,Policy Review Memorandum 84,ISSUE\nPolicy options for licensing review.\n\nMANDATE A...,public,REF-2022-07084

=== public_appointments : 62 lignes, 12 colonnes ===
appointment_record_id          str
appointing_jurisdiction        str
office_holder_name             str
recorded_birth_year        float64
office_title                   str
institution_name               str
appointment_start              str
appointment_end                str
appointment_basis              str
departure_reason               str
official_region                str
source_notice_reference        str
dtype: object

Manquants (%) :
appointment_record_id       0.00
appointing_jurisdiction     0.00
office_holder_name          0.00
recorded_birth_year        14.52
office_title                0.00
institution_name            0.00
appointment_start           0.00
appointment_end            54.84
appointment_basis           0.00
departure_reason           54.84
official_region             0.00
source_notice_reference     0.00
dtype: float64

Lignes dupliquées (strictes) : 0

Échantillon (3 lignes) :

,appointment_record_id,appointing_jurisdiction,office_holder_name,recorded_birth_year,office_title,institution_name,appointment_start,appointment_end,appointment_basis,departure_reason,official_region,source_notice_reference
13,APT-000014,Kintaran,Rayan Belen,1952.0,Agricultural programme director,Avelora Agricultural Resilience Agency,1981-01-01,1992-12-31,appointed,role_transition,Kintaran,NOTICE-KNT-1981-0015
19,APT-000020,Valennan,Nora Yorin,NaN,Programme manager,Orison Medical Audit Board,2015-01-01,2018-12-31,appointed,role_transition,Valennan,NOTICE-VLN-2015-0021
44,APT-000045,Valennan,Taren Norel,1978.0,Senior analyst,Avelora Ministry of Strategic Resources,2002-01-01,2010-12-31,appointed,role_transition,Valennan,NOTICE-VLN-2002-0046

=== registered_entities : 24 lignes, 10 colonnes ===
registration_number               str
legal_name                        str
registered_entity_type            str
registration_date                 str
current_status                    str
registered_address                str
jurisdiction                      str
declared_activity                 str
parent_registration_number    float64
last_filing_date                  str
dtype: object

Manquants (%) :
registration_number             0.0
legal_name                      0.0
registered_entity_type          0.0
registration_date               0.0
current_status                  0.0
registered_address              0.0
jurisdiction                    0.0
declared_activity               0.0
parent_registration_number    100.0
last_filing_date                0.0
dtype: float64

Lignes dupliquées (strictes) : 0

Échantillon (3 lignes) :

,registration_number,legal_name,registered_entity_type,registration_date,current_status,registered_address,jurisdiction,declared_activity,parent_registration_number,last_filing_date
13,REG-VLN-01014,Meridian–Asterion Foundation,foundation,2005-01-15,active,Valenne Central District,Valenne Republic,Public-health and conservation charity,NaN,2025-03-31
10,REG-NDH-01011,Earth Ledger Project,foundation,2014-01-15,active,Nordhaven Maritime District,Nordhaven Union,Corporate-transparency initiative,NaN,2025-03-31
1,REG-VLN-01002,Asterion Clinical Institute,research_institute,1989-01-15,active,Asterion Central Clinical Campus,Valenne Republic,Private preventive-medicine and research institute,NaN,2025-03-31

=== regulatory_case_events : 233 lignes, 16 colonnes ===
regulatory_event_id            str
case_number                    str
case_category                  str
event_time                     str
activity                       str
subject_name                   str
subject_registration_number    str
agency_name                    str
initiating_source              str
assigned_unit                  str
related_site_code              str
related_shipment_number        str
previous_status                str
new_status                     str
outcome                        str
public_reference               str
dtype: object

Manquants (%) :
regulatory_event_id             0.00
case_number                     0.00
case_category                   0.00
event_time                      0.00
activity                        0.00
subject_name                    0.00
subject_registration_number    31.76
agency_name                     0.00
initiating_source               0.00
assigned_unit                   0.00
related_site_code              47.64
related_shipment_number        60.52
previous_status                 0.00
new_status                      0.00
outcome                         0.00
public_reference               66.95
dtype: float64

Lignes dupliquées (strictes) : 1

Échantillon (3 lignes) :

,regulatory_event_id,case_number,case_category,event_time,activity,subject_name,subject_registration_number,agency_name,initiating_source,assigned_unit,related_site_code,related_shipment_number,previous_status,new_status,outcome,public_reference
91,RGE-000092,REG-2022-0016,shipment_inspection,2022-10-17T10:00:00,evidence_received,Kestrel Conservation Services,REG-KNT-20014,Tembara Customs Coordination Unit,routine referral,case review,NaN,SHP-2021-00019,open,evidence_review,records received,NaN
147,RGE-000148,REG-2022-0025,medical_audit,2022-11-03T10:00:00,case_closed,Vale Strategy Collective,REG-VLN-01006,Nordhaven Maritime Safety Agency,routine referral,case review,NaN,NaN,findings_review,closed,case closed without further action,NaN
107,RGE-000108,REG-2016-0018,procurement_review,2016-04-28T10:00:00,case_closed,Velin Packaging Industries,REG-AVL-20021,Avelora Food Standards Office,routine referral,case review,NaN,NaN,findings_review,closed,case closed without further action,NaN

=== site_access_case_events : 413 lignes, 15 colonnes ===
access_event_id                   str
access_case_number                str
site_code                         str
event_time                        str
activity                          str
requesting_organization_name      str
requesting_registration_number    str
authorizing_agency                str
authorized_person_name            str
access_purpose                    str
equipment_category                str
previous_status                   str
new_status                        str
confidentiality_class             str
outcome                           str
dtype: object

Manquants (%) :
access_event_id                    0.00
access_case_number                 0.00
site_code                          0.00
event_time                         0.00
activity                           0.00
requesting_organization_name       0.00
requesting_registration_number    15.74
authorizing_agency                 0.00
authorized_person_name             0.48
access_purpose                     0.00
equipment_category                 0.00
previous_status                    0.00
new_status                         0.00
confidentiality_class              0.00
outcome                            0.00
dtype: float64

Lignes dupliquées (strictes) : 1

Échantillon (3 lignes) :

,access_event_id,access_case_number,site_code,event_time,activity,requesting_organization_name,requesting_registration_number,authorizing_agency,authorized_person_name,access_purpose,equipment_category,previous_status,new_status,confidentiality_class,outcome
143,ACE-000144,ACC-2025-0018,AVL-ORR,2025-06-15T11:00:00,closure_recorded,Horizon Field Research Cooperative,REG-AVL-01013,Avelora Agricultural Resilience Agency,Mara Venn,night wildlife monitoring programme,portable monitoring and cold-storage equipment,completed,closed,confidential,case closed
2,ACE-000003,ACC-2018-0001,TMB-NAC,2018-01-26T09:00:00,wildlife_review,Horizon Field Research Cooperative,REG-AVL-01013,Tembara Biodiversity Service,Jalen Quorin,acoustic monitoring and equipment maintenance,portable monitoring and cold-storage equipment,technical_review,wildlife_review,restricted,wildlife conditions recorded
106,ACE-000107,ACC-2024-0014,KNT-KES,2024-03-01T09:00:00,wildlife_review,Horizon Field Research Cooperative,REG-AVL-01013,Kintara Cave and Pollinator Authority,Liora Corda,night wildlife monitoring programme,acoustic and camera equipment,technical_review,wildlife_review,restricted,wildlife conditions recorded

Création d'une fonction cleaning que j:'appelerais avec des paramètres différents pour chaque table (selon le besoin):
- pour remplir les valeurs manquantes: fillna_map
- convertir les colonnes contenant une date (si le format n'est pas bon): date_cols
- conversion du type de colonne: dtype_map
- vérifier le respect de format: format_checks
- supprimer les doublons selon le primary key (si fourni, on conserve qu'une ligne par key, sinon, on supprime les lignes ENTIEREMENT identiques)

Ajout d'une fonction à part qui traitera la lecture, le type et format des colonnes date

In [31]:
def mixed_dates(series: pd.Series) -> pd.Series:
    """Essaie plusieurs formats de date dans l'ordre, jusqu'à ce que ça marche."""
    formats_to_try = [
        "%Y-%m-%d",                # dates simples
        "%d/%m/%Y",
        "%Y/%m/%d",
        "%Y-%m-%dT%H:%M:%S",       # datetimes avec heure
        "%Y/%m/%d %H:%M:%S",
        "%d-%b-%Y %H:%M:%S",       # ex: 08-Jun-2022 10:00:00
    ]
    parsed = pd.to_datetime(series, format=formats_to_try[0], errors="coerce")

    for fmt in formats_to_try[1:]:
        still_missing = parsed.isna() & series.notna()
        if not still_missing.any():
            break
        parsed.loc[still_missing] = pd.to_datetime(
            series.loc[still_missing], format=fmt, errors="coerce"
        )
    return parsed

Fonction fill_from_duplicate_entity permet de récupérer une information manquante à partir d'une entité dupliquée d'un même fichier.
On utilise cette fonction pour le nettoyage du fichier public_appointments où on veut récupérer l'année de naissance pour un "office_holder_name" qui existe déjà dans le fichier avec l'info nécessaire.
HYPOTHÈSE: on suppose qu'il n'y a pas d'homonyme sur les prénoms, qu'il s'agit de personnes différentes.
- lookup construit une table du type {nom : année de naissance} à partir des infos présentes.
- avec .map() pour récupérer ces infos et combler les vides des colonnes en question

---> inférence de données

In [32]:
def fill_from_duplicate_entity(df: pd.DataFrame, entity_col: str, target_col: str) -> pd.DataFrame:
    df = df.copy()
    lookup = df.dropna(subset=[target_col]).drop_duplicates(subset=[entity_col])
    lookup = lookup.set_index(entity_col)[target_col]

    mask = df[target_col].isna()
    df.loc[mask, target_col] = df.loc[mask, entity_col].map(lookup)
    return df

pour la suppression de ligne, si pk_col est défini, on ne garde qu'une ligne par valeur unique de la PK (deux lignes avec le même registration_number = un doublon, même si le reste diffère) ; si pk_col n'est pas défini, subset=None fait comparer toutes les colonnes (doublon strict, comme df.duplicated() plus haut).

In [33]:
def clean_pipeline(df: pd.DataFrame, name: str, pk_col: str = None,
                    date_cols: list = None, fillna_map: dict = None, format_checks: dict = None) -> pd.DataFrame:
    df = df.copy()

    if fillna_map:
        df = df.fillna(fillna_map)

    if date_cols:
        for c in date_cols:
            df[c] = mixed_dates(df[c])
            # coerce ici permet de transformer les dates invalides en NaT

    before = len(df)
    df = df.drop_duplicates(subset=[pk_col] if pk_col else None)
    if len(df) < before:
        print(f"[{name}] {before - len(df)} doublons supprimés")

    if pk_col:
        n_null = df[pk_col].isna().sum() # on vérifie pk_col == 0 pour être sur quil n'y pas de manquant dans les clés primaires
        n_dup = df[pk_col].duplicated().sum() # pareil, si != 0, il y a des doublons
        status = "OK" if (n_null == 0 and n_dup == 0) else "A VERIFIER"
        print(f"[{name}] PK '{pk_col}' -> {n_null} manquants, {n_dup} doublons [{status}]")

    if format_checks:
        for col, pattern in format_checks.items():
            non_conformes = df[~df[col].astype(str).str.match(pattern, na=False)]
            print(f"[{name}] '{col}' non conformes au pattern : {len(non_conformes)}")

    return df

Création du dictionnaire de configuration CONFIG, avec comme clés externes les noms de fichier, et valeur des dictionnaires des paramètres à passer pour executer la fonction clean_pipeline sur chaque fichier

In [34]:
CONFIG = {
    "registered_entities": {
        "pk_col": "registration_number",
        "date_cols": ["registration_date", "last_filing_date"],
        "format_checks": {
            "registration_number": r'^REG-[A-Z]{3}-\d{5}$',
    },
    },
    "licensed_facilities": {
        "pk_col": "facility_license_number",
        "date_cols": ["license_start", "license_end"],
        "format_checks": {
            "facility_license_number": r'^FAC-[A-Z]{3}-\d{3}$',
            "operating_organization_registration": r'^REG-[A-Z]{3}-\d{5}$',
    },
    },
    "licensed_professionals": {
        "pk_col": "license_number",
        "date_cols": ["license_issue_date", "license_expiry_date"],
        "format_checks": {
            "license_number": r'^LIC-[A-Z]{3}-[A-Z]{3}-\d{4}$',
            },
    },
    "officer_filings": {
        "pk_col": "filing_id",
        "date_cols": ["appointment_date", "cessation_date", "filing_date"],
        "format_checks": {
            "filing_id": r'^FLG-\d{6}$',
            "registration_number": r'^REG-[A-Z]{3}-\d{5}$',
            "officer_local_ref": r'^OFR-\d{5}$',
    },
    },
    "regulatory_case_events": {
        "pk_col": "regulatory_event_id",
        "date_cols": ["event_time"],
        "format_checks": {
            "regulatory_event_id": r'^RGE-\d{6}$',
            "case_number": r'^REG-\d{4}-\d{4}$',
    },
    },
    "site_access_case_events": {
        "pk_col": "access_event_id",
        "date_cols": ["event_time"],
        "format_checks": {
            "access_event_id": r'^ACE-\d{6}$',
            "access_case_number": r'^ACC-\d{4}-\d{4}$',
    },
    },
    "public_appointments": {
        "pk_col": "appointment_record_id",
        "date_cols": ["appointment_start", "appointment_end"],
        "format_checks": {
            "appointment_record_id": r'^APT-\d{6}$',
            "source_notice_reference": r'^NOTICE-[A-Z]{3}-\d{4}-\d{4}$',
    },
    },
    "institutional_memos": {
        "pk_col": "document_id",
        "date_cols": ["document_date"],
        "format_checks": {
            "document_id": r'^MEM-\d{6}$',
    },
    },
    "public_and_investigative_documents": {
        "pk_col": "document_id",
        "date_cols": ["document_date"],
        "format_checks": {
            "document_id": r'^PUB-\d{6}$',
    },
    },
}

## Corrections spécifiques par fichier
Fichiers nécessitants un nettoyage spécifique en plus du général

##### licensed_professionals

In [35]:
df = raw_dfs["licensed_professionals"].copy()
# corrige les espaces multiples dans la colonne specialty
df["specialty"] = df["specialty"].str.strip().str.replace(r"\s+", " ", regex=True)
raw_dfs["licensed_professionals"] = df

##### officer_filings

In [36]:
df = raw_dfs["officer_filings"].copy()
df["full_name"] = df["full_name"].str.strip().str.replace(r"\s+", " ", regex=True)
raw_dfs["officer_filings"] = df

##### public_appointments

In [37]:
df = raw_dfs["public_appointments"].copy()
# corrige les espaces multiples dans la colonne institution_name
df["institution_name"] = df["institution_name"].str.strip().str.replace(r"\s+", " ", regex=True)
# appel de la fonction fill_from_duplicate_entity pour remplir les valeurs manquantes de recorded_birth_year
df = fill_from_duplicate_entity(df, entity_col="office_holder_name", target_col="recorded_birth_year")
raw_dfs["public_appointments"] = df

##### institutional_memos

In [38]:
df = raw_dfs["institutional_memos"].copy()
# corrige les espaces multiples dans la colonne subject_line
df["subject_line"] = df["subject_line"].str.strip().str.replace(r"\s+", " ", regex=True)
raw_dfs["institutional_memos"] = df

## Application et export

In [39]:
clean_dfs = {
    name: clean_pipeline(df, name=name, **CONFIG[name])
    for name, df in raw_dfs.items()
}

[institutional_memos] PK 'document_id' -> 0 manquants, 0 doublons [OK]
[institutional_memos] 'document_id' non conformes au pattern : 0
[licensed_facilities] PK 'facility_license_number' -> 0 manquants, 0 doublons [OK]
[licensed_facilities] 'facility_license_number' non conformes au pattern : 0
[licensed_facilities] 'operating_organization_registration' non conformes au pattern : 0
[licensed_professionals] PK 'license_number' -> 0 manquants, 0 doublons [OK]
[licensed_professionals] 'license_number' non conformes au pattern : 0
[officer_filings] 1 doublons supprimés
[officer_filings] PK 'filing_id' -> 0 manquants, 0 doublons [OK]
[officer_filings] 'filing_id' non conformes au pattern : 0
[officer_filings] 'registration_number' non conformes au pattern : 0
[officer_filings] 'officer_local_ref' non conformes au pattern : 0
[public_and_investigative_documents] PK 'document_id' -> 0 manquants, 0 doublons [OK]
[public_and_investigative_documents] 'document_id' non conformes au pattern : 0
[public_appointments] PK 'appointment_record_id' -> 0 manquants, 0 doublons [OK]
[public_appointments] 'appointment_record_id' non conformes au pattern : 0
[public_appointments] 'source_notice_reference' non conformes au pattern : 0
[registered_entities] PK 'registration_number' -> 0 manquants, 0 doublons [OK]
[registered_entities] 'registration_number' non conformes au pattern : 0
[regulatory_case_events] 1 doublons supprimés
[regulatory_case_events] PK 'regulatory_event_id' -> 0 manquants, 0 doublons [OK]
[regulatory_case_events] 'regulatory_event_id' non conformes au pattern : 0
[regulatory_case_events] 'case_number' non conformes au pattern : 0
[site_access_case_events] 1 doublons supprimés
[site_access_case_events] PK 'access_event_id' -> 0 manquants, 0 doublons [OK]
[site_access_case_events] 'access_event_id' non conformes au pattern : 0
[site_access_case_events] 'access_case_number' non conformes au pattern : 0

## Export des CSV nettoyés

In [40]:
for name, df in clean_dfs.items():
    df.to_csv(f"{name}_cleaned.csv", index=False)

print(f"{len(clean_dfs)} fichiers exportés dans {Path('.').resolve()}")

9 fichiers exportés dans /home/esrapido/G05-DataMining-2627/data/public_records

## Contrôle final — statistiques sur les CSV nettoyés

Construit un tableau récapitulatif : une ligne par fichier, avec les stats clés.
`label` permet de distinguer 'brut' vs 'nettoyé' une fois les deux tableaux combinés.

In [41]:
def summarize_files(dfs: dict, label: str) -> pd.DataFrame:
    rows = []
    for name, df in dfs.items():
        rows.append({
            "fichier": name,
            "etat": label,
            "n_lignes": df.shape[0],
            "n_colonnes": df.shape[1],
            "pct_manquant_moyen": round(df.isna().mean().mean() * 100, 2),
            "colonne_plus_vide": df.isna().mean().idxmax(),
            "pct_max_manquant": round(df.isna().mean().max() * 100, 2),
            "n_doublons": df.duplicated().sum(),
        })
    return pd.DataFrame(rows).sort_values("fichier").reset_index(drop=True)

summary_raw = summarize_files(raw_dfs, "brut")
summary_clean = summarize_files(clean_dfs, "nettoyé")

summary_comparison = pd.concat([summary_raw, summary_clean], ignore_index=True)
summary_comparison = summary_comparison.sort_values(["fichier", "etat"]).reset_index(drop=True)
display(summary_comparison)

,fichier,etat,n_lignes,n_colonnes,pct_manquant_moyen,colonne_plus_vide,pct_max_manquant,n_doublons
0,institutional_memos,brut,30,12,18.61,related_purchase_order,83.33,0
1,institutional_memos,nettoyé,30,12,18.61,related_purchase_order,83.33,0
2,licensed_facilities,brut,3,12,8.33,license_end,100.00,0
3,licensed_facilities,nettoyé,3,12,8.33,license_end,100.00,0
4,licensed_professionals,brut,53,10,14.91,license_expiry_date,100.00,0
5,licensed_professionals,nettoyé,53,10,14.91,license_expiry_date,100.00,0
6,officer_filings,brut,136,12,4.72,cessation_date,56.62,1
7,officer_filings,nettoyé,135,12,4.75,cessation_date,57.04,0
8,public_and_investigative_documents,brut,40,11,0.23,author_name,2.50,0
9,public_and_investigative_documents,nettoyé,40,11,0.23,author_name,2.50,0
10,public_appointments,brut,62,12,9.95,appointment_end,54.84,0
11,public_appointments,nettoyé,62,12,9.95,appointment_end,54.84,0
12,registered_entities,brut,24,10,10.00,parent_registration_number,100.00,0
13,registered_entities,nettoyé,24,10,10.00,parent_registration_number,100.00,0
14,regulatory_case_events,brut,233,16,12.93,public_reference,66.95,1
15,regulatory_case_events,nettoyé,232,16,12.88,public_reference,66.81,0
16,site_access_case_events,brut,413,15,1.08,requesting_registration_number,15.74,1
17,site_access_case_events,nettoyé,412,15,1.08,requesting_registration_number,15.78,0